# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
      };
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      availableKernelModules = [
      ];
      kernelModules = [ ];
      luks.devices = {
        "luks-f61c12a1-ffc3-4e66-9d3e-ed879e8c585a" = {
          crypttabExtraOpts = [ "fido2-device=auto" ];
          device = "/dev/disk/by-uuid/f61c12a1-ffc3-4e66-9d3e-ed879e8c585a";
        };
        "luks-a5737fa5-ed8a-487a-84d7-f0cdbd676b5f".device =
          "/dev/disk/by-uuid/a5737fa5-ed8a-487a-84d7-f0cdbd676b5f";
      };
      systemd.enable = true;
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/29d0f63b-3bcb-4113-b8fc-54315e7d655d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4085-8EB0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/dd8ed16f-75cf-41ff-9d3b-375b744a00a9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable OpenGL
  hardware.graphics = {
    enable = true;
  };
}
